Update git hook files
  - Updating the messages
  - Adding more validations

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,7 +1,9 @@
 #!/bin/bash
 # https://gist.github.com/rashtay/328da46a99a9d7c746636df1cf769675
 
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
+echo "[pre-commit]: START"
+
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
 ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
 
 if [[ "$STAGED_FILES" = "" ]]; then
@@ -10,11 +12,9 @@ fi
 
 PASS=true
 
-printf "\nValidating Javascript:\n"
-
 # Check for eslint
 if [[ ! -x "$ESLINT" ]]; then
-  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
+    echo "[pre-commit]: Please install eslint"
   exit 1
 fi
 
@@ -22,21 +22,15 @@ for FILE in $STAGED_FILES
 do
   "$ESLINT" "$FILE"
 
-  if [[ "$?" == 0 ]]; then
-    printf "\t\033[32mESLint Passed: $FILE\033[0m"
-  else
-    printf "\t\033[41mESLint Failed: $FILE\033[0m"
+  if ! [[ "$?" == 0 ]]; then
     PASS=false
   fi
 done
 
-printf "\nJavascript validation completed!\n"
-
 if ! $PASS; then
-  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
+  echo "[pre-commit]: Fix eslint errors and try again"
   exit 1
-else
-  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
 fi
 
-exit $?
+echo "[pre-commit]: Commit succeeded"
+exit 0
diff --git a/.hooks/pre-push b/.hooks/pre-push
--- a/.hooks/pre-push
+++ b/.hooks/pre-push
@@ -5,14 +5,20 @@
 # https://gist.github.com/pixelhandler/5718585#gistcomment-840997
 # https://gist.github.com/pixelhandler/5718585#gistcomment-1390358
 
-BRANCH=`git rev-parse --abbrev-ref HEAD`
+echo "[pre-push]: START"
 PUSH_COMMAND=`ps -ocommand= -p $PPID`
-PROTECTED_BRANCHES="(master|dev|release-*|patch-*)"
-FORCE_PUSH="force|delete|-f"
+PROTECTED_REMOTE_BRANCHES="(master|release-*|patch-*)"
 
-if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
-  echo "Prevented force-push to protected branch \"$BRANCH\" by pre-push hook"
-  exit 1
-fi
+# Check the file of example pre-push.sample to get variables
+while read local_ref local_sha remote_ref remote_sha
+do
+  echo "[pre-push]: Trying to push towards the branch $remote_ref"
+  BRANCH_TO_PUSH="$remote_ref"
+  if [[ "$BRANCH_TO_PUSH" =~ $PROTECTED_REMOTE_BRANCHES ]]; then
+      echo "[pre-push]: Failed to push to \"$BRANCH_TO_PUSH\" because is blocked by the repository owner"
+      exit 1
+  fi
+done
 
+echo "[pre-push]: Push to $BRANCH_TO_PUSH succeeded"
 exit 0
